/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

import control.ClienteControl;
import persistence.Tallerista;
import view.TallerFrame;

import java.awt.Color;
import javax.swing.AbstractAction;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;

import javax.swing.Action;

/**
 *
 * @author Dell
 */
public class Login extends javax.swing.JFrame {

	/**
	 * Creates new form Login
	 */
	private ClienteControl cc;

	public Login() {
		initComponents();
		this.lab4.setVisible(false);

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		lab9 = new javax.swing.JLabel();
		lab4 = new javax.swing.JLabel();
		panel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		emailText = new javax.swing.JTextField();
		passText = new javax.swing.JPasswordField();
		jLabel3 = new javax.swing.JLabel();
		jPanel5 = new javax.swing.JPanel();
		lab6 = new javax.swing.JButton();

		jSeparator1 = new javax.swing.JSeparator();
		jSeparator2 = new javax.swing.JSeparator();
		lab8 = new javax.swing.JLabel();
		lab7 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		lab1 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();

		try {
			cc = new ClienteControl();
		} catch (RemoteException e1) {
			e1.printStackTrace();
		} catch (NotBoundException e1) {
			e1.printStackTrace();
		}

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setLocation(new java.awt.Point(250, 100));
		setUndecorated(true);
		getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		lab9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgs/icons8_Cancel_30px.png"))); // NOI18N
		lab9.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				lab9MousePressed(evt);
			}
		});
		jPanel1.add(lab9, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, 30, 40));

		lab4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgs/icons8_New_Post_32px.png"))); // NOI18N
		lab4.setText("jLabel3");
		jPanel1.add(lab4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 40, 50));

		panel1.setBackground(new java.awt.Color(51, 51, 51));
		panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
		// Email

		jLabel2.setForeground(new java.awt.Color(255, 255, 255));
		jLabel2.setText("Email");
		jLabel2.addFocusListener(new java.awt.event.FocusAdapter() {
			public void focusGained(java.awt.event.FocusEvent evt) {
				jLabel2FocusGained(evt);
			}

			public void focusLost(java.awt.event.FocusEvent evt) {
				jLabel2FocusLost(evt);
			}
		});
		jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jLabel2MousePressed(evt);
			}
		});
		panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 200, 30));

		jLabel4.setFont(new java.awt.Font("Trebuchet MS", 0, 11)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(255, 255, 255));
		jLabel4.setText("Password");
		jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mousePressed(java.awt.event.MouseEvent evt) {
				jLabel4MousePressed(evt);
			}
		});
		panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 200, 30));

		jPanel4.setBackground(new Color(0, 128, 0));

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout.setHorizontalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 130, Short.MAX_VALUE));
		jPanel4Layout.setVerticalGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 10, Short.MAX_VALUE));

		panel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, 10));

		emailText.setBackground(new java.awt.Color(51, 51, 51));
		emailText.setForeground(new java.awt.Color(255, 255, 255));
		emailText.setBorder(null);
		emailText.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				jTextField2KeyTyped(evt);
			}
		});
		panel1.add(emailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 230, 30));

		passText.setBackground(new java.awt.Color(51, 51, 51));
		passText.setForeground(new java.awt.Color(255, 255, 255));
		passText.setBorder(null);
		passText.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jPasswordField1ActionPerformed(evt);
			}
		});
		passText.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyTyped(java.awt.event.KeyEvent evt) {
				jPasswordField1KeyTyped(evt);
			}
		});
		panel1.add(passText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 230, 30));

		jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgs/icons8_Lock_32px.png"))); // NOI18N
		panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, 50));

		jPanel5.setBackground(new java.awt.Color(51, 51, 51));
		jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 255)));
		jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		// ---------------------------------------------------BOTON-------------------------------------------------------

		lab6.setBackground(Color.BLACK);
		lab6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
		lab6.setForeground(new java.awt.Color(255, 255, 255));
		lab6.setText("Ingresar");
		lab6.setToolTipText("");
		lab6.addActionListener(new ActionListener() { // EVENTO
			public void actionPerformed(ActionEvent e) {
				System.out.println("click");
				System.out.println(emailText.getText());
				System.out.println(passText.getText());
				search(emailText.getText(), passText.getText());

			}
		});

		// ---------------------------------------------------BOTON-------------------------------------------------------

		jPanel5.add(lab6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 50));

		panel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 280, 50));
		panel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 230, 20));
		panel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 230, 10));

		lab8.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
		lab8.setForeground(new java.awt.Color(255, 255, 255));
		lab8.setText("Login");
		panel1.add(lab8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, 50));

		lab7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgs/icons8_User_35px_1.png"))); // NOI18N
		lab7.setText("jLabel3");
		panel1.add(lab7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 40, 50));

		jPanel1.add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 320, 370));

		jPanel2.setBackground(new java.awt.Color(51, 204, 255));

		lab1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		lab1.setForeground(new java.awt.Color(51, 51, 51));
		lab1.setText("     Sign in");
		lab1.addMouseListener(new java.awt.event.MouseAdapter() {

		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(lab1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
						110, Short.MAX_VALUE));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(lab1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE,
						40, Short.MAX_VALUE));

		jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 110, 40));

		jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imgs/484717.jpg"))); // NOI18N
		jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));

		getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, -1));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void lab9MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_lab9MousePressed
		System.exit(0);
	}

	private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel2MousePressed
		jLabel2.setVisible(false);
		emailText.setVisible(true);

// TODO add your handling code here:
	}// GEN-LAST:event_jLabel2MousePressed

	private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jPasswordField1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jPasswordField1ActionPerformed

	private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel4MousePressed
		jLabel4.setVisible(false);
		passText.setVisible(true);
		// TODO add your handling code here:
	}// GEN-LAST:event_jLabel4MousePressed

	private void jTextField2KeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jTextField2KeyTyped
		// we have give the condition to Jtextfield for setVisible the label true

	}// GEN-LAST:event_jTextField2KeyTyped

	private void jPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_jPasswordField1KeyTyped

// TODO add your handling code here:
	}// GEN-LAST:event_jPasswordField1KeyTyped

	private void jLabel2FocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jLabel2FocusLost

		// TODO add your handling code here:
	}// GEN-LAST:event_jLabel2FocusLost

	private void jLabel2FocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_jLabel2FocusGained
		// TODO add your handling code here:
	}// GEN-LAST:event_jLabel2FocusGained

	public void search(String mail, String contra) {

		boolean exists = false;
		String Pass = "admin123";

		for (Tallerista t : cc.searchTallerista()) {

			if (t.getEmail().equals(mail)) {
				System.out.println("Bienvenido");

				exists = true;
			}
		}

		if (!exists) {
			System.out.println("User Not Found");
			JOptionPane.showMessageDialog(null, "El usuario no existe", "ERROR", JOptionPane.ERROR_MESSAGE);
			emailText.setText("");
			passText.setText("");
		} else {
			if (contra.equals(Pass)) {
				try {
					UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
				} catch (ClassNotFoundException | InstantiationException | IllegalAccessException
						| UnsupportedLookAndFeelException ex) {
					ex.printStackTrace();
				}

				TallerFrame tf = new TallerFrame();
				tf.setSize(720, 450);
				JOptionPane.showMessageDialog(null, "Ingresaste correctamente", "EXITO",
						JOptionPane.INFORMATION_MESSAGE);
				tf.setResizable(false);
				tf.setLocationRelativeTo(null);
				this.setVisible(false);

				tf.setVisible(true);

				this.dispose();
				tf.repaint();

			} else {
				JOptionPane.showMessageDialog(null, "Contraseña Incorrecta", "ERROR", JOptionPane.ERROR_MESSAGE);
				passText.setText("");
			}
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */

		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Login().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPasswordField passText;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JSeparator jSeparator2;
	private javax.swing.JTextField emailText;
	private javax.swing.JLabel lab1;
	private javax.swing.JLabel lab4;
	private JButton lab6;
	private javax.swing.JLabel lab7;
	private javax.swing.JLabel lab8;
	private javax.swing.JLabel lab9;
	private javax.swing.JPanel panel1;
	private final Action action = new SwingAction();

	// End of variables declaration//GEN-END:variables
	private class SwingAction extends AbstractAction {
		public SwingAction() {
			putValue(NAME, "SwingAction");
			putValue(SHORT_DESCRIPTION, "Some short description");
		}

		public void actionPerformed(ActionEvent e) {
		}
	}
}
